### ISSUE TITLE
doesn't compile on arch linux.

### ISSUE THREAD

**Issue by ghost** [lwfinger/realtek_bluetooth#1]
```
[arun@hp realtek_bluetooth]$ make
make -C /lib/modules/4.10.4-1-ck-skylake/build M=/tmp/realtek_bluetooth modules
make[1]: Entering directory '/usr/lib/modules/4.10.4-1-ck-skylake/build'
  CC [M]  /tmp/realtek_bluetooth/btusb.o
In file included from /tmp/realtek_bluetooth/btusb.c:35:0:
/tmp/realtek_bluetooth/bt_compat.h:17:19: error: static declaration of ‘hci_recv_diag’ follows non-static declaration
 static inline int hci_recv_diag(struct hci_dev *hdev, struct sk_buff *skb)
                   ^~~~~~~~~~~~~
In file included from /tmp/realtek_bluetooth/btusb.c:30:0:
./include/net/bluetooth/hci_core.h:1031:5: note: previous declaration of ‘hci_recv_diag’ was here
 int hci_recv_diag(struct hci_dev *hdev, struct sk_buff *skb);
     ^~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:301: /tmp/realtek_bluetooth/btusb.o] Error 1
make[1]: *** [Makefile:1494: _module_/tmp/realtek_bluetooth] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.10.4-1-ck-skylake/build'
make: *** [Makefile:62: all] Error 2
[arun@hp realtek_bluetooth]$ 
```
do I need opensuse to build this module?
thanks.

**Comment by lwfinger** [comment]
No, you do not need openSUSE. Yhis repo has essentually been abandoned in favor of rtl8723au_bt.git. Given the potential for misunderstanding the name of the other repo, I have copied all its files into this repo and pushed them.

BTW, with a kernel as new as 4.10.4, I am surprised that you need to use an external driver. As far as I know, the one in the 4.10 kernel is the same as this one.

**Comment by ghost** [comment]
my laptop has this adapter rtl8723be inbuilt. WiFi is working with stock kernel but Bluetooth doesn't.
`[arun@hp ~]$ bluetoothctl
[NEW] Controller XX:XX:XX:XX:XX:XX hp [default]
[bluetooth]# power on
Failed to set power on: org.bluez.Error.Failed
[bluetooth]# scan on
Failed to start discovery: org.bluez.Error.NotReady
[bluetooth]# devices
[bluetooth]# 
`

**Comment by zhilyaev** [comment]
me too @arunsai123

**Comment by zhilyaev** [comment]
how install?

[diamon@diamon-pc realtek_bluetooth-master]$ make
make -C /lib/modules/4.9.16-1-MANJARO/build M=/home/diamon/Загрузки/realtek_bluetooth-master modules
make[1]: вход в каталог «/usr/lib/modules/4.9.16-1-MANJARO/build»
make[1]: *** Нет правила для сборки цели «modules».  Останов.
make[1]: выход из каталога «/usr/lib/modules/4.9.16-1-MANJARO/build»
make: *** [Makefile:25: all] Ошибка 2
[diamon@diamon-pc realtek_bluetooth-master]$ sudo make install
[sudo] пароль для diamon: 
cp: не удалось выполнить stat для '*_fw.bin': Нет такого файла или каталога
make: *** [Makefile:33: install] Ошибка 1
[diamon@diamon-pc realtek_bluetooth-master]$

**Comment by ghost** [comment]
@zhilyaev you can't compile it with newer kernel.

**Comment by lwfinger** [comment]
@ arunsai123: That is not correct. The only problem was that it was looking for the firmware in the wrong directory when installing. It failed for ALL kernels. The problem is now fixed. Do a "git pull".

@zhilyaev I do not read Russian, and Google Translate had some problems, but you need to do a "git pull" and perhaps a "sudo pacman -S linux-headers". The make should then work.

I tried to download the Arch ISO and build a working version in a virtual machine. The installation reminded me of 1990 when I first started with Linux. I never did get a working boot. Fortunately, I found a pre-made VM and downloaded it. That way I could get a machine on which to test.
